### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'manifest_file'

### ISSUE THREAD

**Issue by kimgh06** [meta-llama/llama-models#114]
![image](https://github.com/user-attachments/assets/afc5cd3e-401a-4420-bd80-1f0db2f4d05d)

**Comment by ashwinb** [comment]
I fixed this with https://github.com/meta-llama/llama-stack/commit/e08e963f861b9c44f80ac351c79cd9bc1c54000d. Will publish an updated package soon. Sorry about that.

**Comment by ashwinb** [comment]
Uploaded https://pypi.org/project/llama-toolchain/0.0.8/ -- please try again and re-open if the issue persists.

**Comment by kimgh06** [comment]
THX!
