### ISSUE TITLE
Put back the content of  PR https://github.com/meta-llama/llama-models/pull/108 into main. 

### ISSUE THREAD

**Issue by whatdhack** [meta-llama/llama-models#118]
Someone  inadvertently pushed another  PR  which probably had stale content and  wiped out the contents of this already merged PR.

**Comment by ashwinb** [comment]
@whatdhack The content just changed location? It is in models/scripts/ instead of in the llama3_1 sub-folder. The top-level README has also been updated. See https://github.com/meta-llama/llama-models?tab=readme-ov-file#running-the-models

**Comment by whatdhack** [comment]
Thanks for the clarification,  The scripts moved and also the generation.py and model.py files  from 3.1 to 3.0 directory.  Thanks for updating the README also .

**Comment by whatdhack** [comment]
@ashwinb ,   I have a question that is tangentially related. The model directory is called reference_impl. That implies there are other implementations.  Is there a pure PyTorch implementation  using torch.distributed.tensor.parallel instead of fairscale.nn.model_parallel ? Also, it will be good to have a list of other known implementations - pure PyTorch or not.
