### ISSUE TITLE
Is there a way to specify download location

### ISSUE THREAD

**Issue by Andy-LZH** [meta-llama/llama-models#134]
Hello there, my cluster has some restricted storage of the $HOME spaces and our team used a shared folder for downloading model weights. I'm wondering is there any way to specify a download location in the `llama` cli or is there any workarounds. Thx in advance

**Comment by XinWang-OU** [comment]
Same question here!

**Comment by XinWang-OU** [comment]
This answer workds on me:
https://github.com/OpenInterpreter/open-interpreter/issues/159#issuecomment-2323450780

**Comment by Andy-LZH** [comment]
That worked for me as well!
