### ISSUE TITLE
Llama 3.1 Download Instructions readme missing

### ISSUE THREAD

**Issue by epelc** [meta-llama/llama-models#14]
https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/README.md is a 404/missing file.

After filling out a download request the link given for download instructions is a 404.

<img width="1113" alt="image" src="https://github.com/user-attachments/assets/0e99c953-b0a0-4ee1-836e-5abed5b8cb29">

**Comment by ashwinb** [comment]
Fixed!
