### ISSUE TITLE
Grouped Query Attention Missing (n_kv_heads = None) ?

### ISSUE THREAD

**Issue by el-hash-1** [meta-llama/llama-models#149]
In the reference implementation the n_kv_heads is set to None by default.  [link](https://github.com/meta-llama/llama-models/blob/main/models/llama3/api/args.py#L17)

Then how is Attention going to be a "Grouped Query Attention" ? Are we supposed to set it ourselves? Wouldn't it affect the performance if we deviate from the one that was used during training ? @ashwinb

**Comment by ashwinb** [comment]
This default is only in code. It is typically provided by the `params.json` that goes along with the model. See 
https://github.com/meta-llama/llama-models/blob/main/models/sku_list.py#L464
for example. This is the GQA setting.

If not specified it falls back to standard MHA: 
https://github.com/meta-llama/llama-models/blob/main/models/llama3/reference_impl/model.py#L118
