### ISSUE TITLE
RoPE scale factor for llama3.2

### ISSUE THREAD

**Issue by NTT123** [meta-llama/llama-models#166]
We are using a scale factor of `8` in the reference implementation, which seems to match with Hugging Face config files for 3.1 models.

However, I observed that the new 3.2 models use a scale factor of `32` (https://huggingface.co/meta-llama/Llama-3.2-1B/blob/main/config.json#L23). I wonder if this can cause any potential issues?
https://github.com/meta-llama/llama-models/blob/4269717b2ea587627903bacbb75ccce1427ad914/models/llama3/reference_impl/model.py#L47

**Comment by karan-dalal** [comment]
+1

**Comment by karan-dalal** [comment]
After running some long context eval, 32 seems to be the correct scale factor @NTT123

**Comment by cglagovichTT** [comment]
@varunfb what is the correct scale factor? Is the issue incorrect in saying it should be 32?

**Comment by varunfb** [comment]
@cglagovichTT It should be 32 as documented in the config. json for Llama 3.2 model.

**Comment by cglagovichTT** [comment]
thanks @varunfb. Doesn't that mea that this issue should stay open since the reference model incorrectly uses a scale_factor of 8 for llama3.2 models?

**Comment by varunfb** [comment]
The model referenced above or the [link](https://github.com/meta-llama/llama-models/blob/4269717b2ea587627903bacbb75ccce1427ad914/models/llama3/reference_impl/model.py#L47) is pointing to Llama 3 not Llama 3.2

**Comment by cglagovichTT** [comment]
yes but that is the reference model used when running Llama3.2
