### ISSUE TITLE
How can I get the python file of the model architecture, such as 'model.py' ?

### ISSUE THREAD

**Issue by LaosGAmin** [meta-llama/llama-models#171]
I want to make some changes to the model, but using the transforms packet seems a bit inconvenient.

**Comment by raghotham** [comment]
https://github.com/meta-llama/llama-models/blob/main/models/llama3/reference_impl/model.py

**Comment by LaosGAmin** [comment]
> https://github.com/meta-llama/llama-models/blob/main/models/llama3/reference_impl/model.py
Yes, I know LLAMA3, but how about llama3.2 or vision?
