### ISSUE TITLE
Download model errors

### ISSUE THREAD

**Issue by barrontang** [meta-llama/llama-models#173]
I have successfully downloaded  model Llama-Guard-3-11B-Vision. When I tried to download Meta-Llama-3.1-8B through https://llama3-1.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiZ3hvZDkxZTlocTM4b3oxcG1vdXM1YW03IiwiUmVzb3VyY2UiOiJodHRwc....
the server response with 403 Forbidden error as following:
Connecting to llama3-1.llamameta.net (llama3-1.llamameta.net)|108.156.133.21|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-10-10 17:36:59 ERROR 403: Forbidden.

How to solve this problem? Thanks.

**Comment by Jhyuny** [comment]
i have the same error.. :( how can we fix it?

**Comment by raghotham** [comment]
You may run into this problem if you are in a region where download is not available.
