### ISSUE TITLE
Downloading and running model - errors

### ISSUE THREAD

**Issue by Opfour** [meta-llama/llama-models#196]
Installed llama via info from https://www.llama.com/llama-downloads/ using the `pip install llama-stack` command. Running the command to retrieve model types, I see the following warning:
(same error seen with  `llama model list`

`user@Merovingian2:~$ llama model list --show-all
/home/david/.local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:172: UserWarning: Field name "schema" in "JsonResponseFormat" shadows an attribute in parent "BaseModel"
  warnings.warn(`

It does display a listing of the models, but when trying to run any of the models, I see:

`user@Merovingian2:~$ llama model download --source meta --model-id Llama-3.2-3B/home/david/.local/lib/python3.12/site-packages/pydantic/_internal/_fields.py:172: UserWarning: Field name "schema" in "JsonResponseFormat" shadows an attribute in parent "BaseModel"
  warnings.warn(
usage: llama model download [-h] [--source {meta,huggingface}]`

                           `[--model-id MODEL_ID] [--hf-token HF_TOKEN]
                            [--meta-url META_URL]
                            [--ignore-patterns IGNORE_PATTERNS]
                            [--manifest-file MANIFEST_FILE]`
`llama model download: error: Model Llama-3.2-3B not found`

is the naming scheme in the list wrong or am I missing part of the name? e.g. 
`meta-llama/Llama-3.2-3B`

**Comment by ashwinb** [comment]
![image](https://github.com/user-attachments/assets/6457cb43-a9e2-42b9-aa92-ec3d26031992)

Use the descriptors from the first column. For example:
- Llama3.2-3B-Instruct
- Llama3.2-3B-Instruct:int4-qlora-eo8

etc.

**Comment by Opfour** [comment]
Noted and thank you!
