### ISSUE TITLE
Possible small issue with descriptor method of Model class in datatypes.py

### ISSUE THREAD

**Issue by Maiguek** [meta-llama/llama-models#209]
I was having problems downloading the Llama3.2 quantized instruct models, as the combo of model_id + variant was defined as a string of `f"{self.core_model_id.value}:{self.variant}"`, in line 197 of datatypes.py. 

The ":" was causing a system error while trying to create a folder with this name on Windows, and modifying it by a "-" like this -> `f"{self.core_model_id.value}-{self.variant}"` solved my problem 🍡

**Comment by varunfb** [comment]
Thank you for reporting the issue. @ashwinb this is something we have to fix based on the machine these commands are run?

**Comment by ashwinb** [comment]
Fixed this with https://github.com/meta-llama/llama-stack/commit/285cd26fb242a7e5d87ec66bea437f3a62e0eeea

The next version of the llama-stack package will have this fixed.
