### ISSUE TITLE
Download link broken for Llama 3.1-405b-Instruct FP8

### ISSUE THREAD

**Issue by chotzen** [meta-llama/llama-models#21]
Hello,

I'm able to download the other checkpoint formats for Llama 3.1-405b-Instruct. However, when I try to download the fp8 weights it sends a request to this URL (after successfully downloading the tokenizer)

`https://llama3-1.llamameta.net/Meta-Llama-3.1-405B-Instruct/consolidated.00.pth?Policy=[...]&Signature=[...]&Key-Pair-Id=[...]&Download-Request-ID=[...]`

And this request returns HTTP Error 400.

Additionally, I believe there is a typo in the script (it says `fb8` in one place instead of `fp8`). See here: https://github.com/chotzen/llama-models/commit/30abaacafe0e44dc58d32d2a2bbe49bd3cd82058

Please let me know if there is any more information you need to help reproduce this.

**Comment by alphrc** [comment]
Same

**Comment by chotzen** [comment]
it seems that this checkpoint is not in the same `consolidated-XX.pth` format, and the shards are themselves sharded further along the layer dimension. 

This is according to the huggingface repo: https://huggingface.co/meta-llama/Meta-Llama-3.1-405B-Instruct-FP8/tree/main

**Comment by samuelselvan** [comment]
#22 will merge soon and confirm

**Comment by flammit** [comment]
Still broken after the `s/fb8/fp8` fix in #22.  Getting `400 Bad Request` when trying to retrieve any of the PTH files for either of the FP8 models.

**Comment by samuelselvan** [comment]
Am checking this. It looks to be due to file sizes. Will update soon.

**Comment by craftofknowing** [comment]
Same issue!

**Comment by helixzz** [comment]
Same issue.

**Comment by othmane-pocket** [comment]
Same issue. I am able to download `Meta-Llama-3.1-405B-Instruct-MP16` but the other models give the:
```
Downloading consolidated.00.pth
--2024-07-25 12:37:23--  https://llama3-1.llamameta.net/Meta-Llama-3.1-405B-Instruct-MP8/consolidated.00.pth?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoibTFqYWQ4aGlvZHE5d3k2d2VqZm53c2JmIiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMTk5Njg0N319fV19&Signature=XUEonUvQgF-Hts8Cd3DfpTxa0HeCX4DQwlLfpvWOIFMLcDXpBmxG9yMVue37OdBwJUFvgzHBboYIrcJTkKXuLyUeyLkt7pFGbcbf4sgmdPk1Gp1B30NxYXFdc6btILiybEbo5crOLc7PkGZk3yrQXJ5rOn5%7EShg4DadS4C-K4sG699IOV84JwfHtcYxMmt4SgIKj%7EzYcz70lgN5YrkfjNquRIYHuTOmpE6orDU5FHIkfAd4ivdjAArvDiWjWfUWI55-BgZbTg0uCX5cII8iO0dqbtNxeqbUKYAaWlviJgDE%7EzgTsr0d0pGTtuQkIfrwj35NqVOCmP6d25mZVBCt5Mg__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=361806533628345
Resolving llama3-1.llamameta.net (llama3-1.llamameta.net)... 108.156.133.3, 108.156.133.14, 108.156.133.21, ...
Connecting to llama3-1.llamameta.net (llama3-1.llamameta.net)|108.156.133.3|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2024-07-25 12:37:24 ERROR 400: Bad Request.
```

**Comment by zhangry868** [comment]
Same here. I tried multiple times. All 405B-Instruct checkpoints do not work.

**Comment by samuelselvan** [comment]
Can you all try with the latest download.sh. I did merge #22 and tested for Meta-Llama-3.1-405B-Instruct-MP8 and it took 9 hours with good internet.

**Comment by helixzz** [comment]
> Can you all try with the latest download.sh. I did merge #37 and tested for Meta-Llama-3.1-405B-Instruct-MP8 and it took 9 hours with good internet.

Thanks! 
I'm trying and seems there are two new problems:

1. I've already downloaded Meta-Llama-3.1-405B-Instruct-MP16 using the previous version of the script. The new script cannot recognize the *.pth (47.7GiB each) that was already downloaded and started over again. That's painful.
2. The download speed is significantly reduced after switching to cURL. We've got stable 110MiB/s with a 1Gbps link before, and now we're stuck on about 10~15MiB/s.

**Comment by samuelselvan** [comment]
@helixzz valid points and I did notice. Unfortunately they are limitations with wget and curl around ranged chunk downloads and —continue options.
At least this unblocks, and am exploring options.

**Comment by helixzz** [comment]
> @helixzz valid points and I did notice. Unfortunately they are limitations with wget and curl around ranged chunk downloads and —continue options. At least this unblocks, and am exploring options.

Yeah it is. Thanks!

**Comment by helixzz** [comment]
> > @helixzz valid points and I did notice. Unfortunately they are limitations with wget and curl around ranged chunk downloads and —continue options. At least this unblocks, and am exploring options.
> 
> Yeah it is. Thanks!

Okay. I think it's hardly usable without the ability to resume from last (break) point. 

The annoying point is that I've tried for several days and the script always fails at some random point (e.g. got HTTP 400 while downloading the Nth file). And I have to delete all downloaded files to start over from the beginning because the script just append to the consolidated.xx.pth file instead of recognize and skip them. 

Sad to say, but that really makes the download never ends. =(

**Comment by tiagonix** [comment]
Yeah, @helixzz, I'm also seeing this problem, the download never ends.

I'm trying to download `Meta-Llama-3.1-405B-Instruct-MP16`.

However, it fails to finish in 24H, the token expires, then, I have to start over from the beginning because the script doesn't support resuming the download! It just happened again.

I'm using the latest `main` Git branch.

The `download.sh` script should support resuming!

**Comment by tiagonix** [comment]
Today it stopped with: `curl: (56) OpenSSL SSL_read: Connection timed out, errno 110` - Very frustrating...  :-/

**Comment by tiagonix** [comment]
Still doesn't work...
I'm trying to download `meta-llama-3.1-405b` for more than a week. And I do have very good Internet connection.
Today error was: `curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104`.

**Comment by tiagonix** [comment]
After much insistence, I'm finishing downloading the 405B models! But one by one, and one per token/24H.
The download link (related to this issue seems to be fixed).

**Comment by ashwinb** [comment]
Thanks for your patience! We made a few improvements to this process with the `llama download` CLI, hopefully experience is better for others...
