### ISSUE TITLE
store directly to cloud

### ISSUE THREAD

**Issue by MalikRumi** [meta-llama/llama-models#211]
Ok, this is completely my own fault. I'm downloading several models when it hits me I need more space. 

1. Do I need a new or different download url to send the larger models directly to my cloud and or hosting provider?
2. I'm probably going to need more time anyway, because my 48 hours expires today.

Please advise. Thanks.

**Comment by varunfb** [comment]
Download time is going to depend on the bandwidth you end up having. Typically the download should restart from where you left off.
