### ISSUE TITLE
Image input is not working for Llama-3.2-3B-Instruct.Q6_K.llamafile

### ISSUE THREAD

**Issue by navaneethsunil98** [meta-llama/llama-models#218]
I've been running the Llama-3.2-3B-Instruct.Q6_K.llamafile on my PC and I've been trying to upload images using the the Upload image button on the browser interface on http://127.0.0.1:8080/. Whenever I upload an image and ask a question based on it a message pops up saying:

The server was not compiled for multimodel or the model projector can't be loaded. I've found the same issue for various other llamafile models that I've used. 

I've been running this models on a windows machine. I've attached a screenshot of my interface response. Can someone please let me know if these llamafile models can process images? I'd like to use it as OCRs sometimes if that's possible?

![Multimodel issue Llama 3 2](https://github.com/user-attachments/assets/1f4219bd-22d8-4950-be19-d58429b5a604)

**Comment by ashwinb** [comment]
I don't think this is the correct forum for questions about llamafile.
