### ISSUE TITLE
403 forbidden 

### ISSUE THREAD

**Issue by Rupalestine** [meta-llama/llama-models#221]
!wget -O Meta-Llama-Guard-3-8B.pth "https://llama3-1.llamameta.net/?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiMjBveWJjMjB6ODVnOHgwOTE4bnY1aDV0IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczMTc0NDAxNn19fV19&Signature=Qb0SCeJranOUCFoJNYobTTd%7EFYYSf-ZdIIeHG76NuG39Ar6yHg5hkYgbVjjSVO7pXlz3R3Jj68KnpNPfSNEICvZpoNlB3tI5Mc7hGAwjWHzrZCNa5kYvI8pWAIoyTZPjLJyV4JCjwZBkM5UE5AyjYTj-67OzTN72JKgpIyJNJKri4xI7LVDo7YrA1PmQH1OkUnH%7EeJKeIdMDuZ-hVD973zLoVoE3RDYQrWcWSsyi8ofCoqUMnfOEJrCii83VC%7EoP26D-g%7E3O3VoSPzpvijaGzg%7EkODLie5yOw1y826oGv3jsWskWh6ER369nWzWDLWJx-RRuqm990hj-Bpxeo9B%7EwA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=928036362538761"   i revceive demail few hours ago only

**Comment by ashwinb** [comment]
Your URL doesn't have the correct sub-path. We don't support using `wget` directly with that URL since the sub-path needs to be filled with several files which need to be downloaded individually.

Please use `llama model download` as per instructions in the repository.

**Comment by kalyani7195** [comment]
I am getting the same error 405 forbidden. I followed all the instructions.
