### ISSUE TITLE
Why are you doing this?

### ISSUE THREAD

**Issue by cloud9tn** [meta-llama/llama-models#25]
Just make the models available in a simpler fashion so we stop running into errors like every single release.

Reusing existing connection to llama3-1.llamameta.net:443.
HTTP request sent, awaiting response... 403 Forbidden.
2024-07-23 22:27:32 ERROR 403: Forbidden..

**Comment by Sovenok-Hacker** [comment]
Yes, I have also got into something like that ...

**Comment by samuelselvan** [comment]
@cloud9tn @Sovenok-Hacker - can you try getting a new url and retry? If you face issues, can I have the request id or the last part if the url with Download-Request-ID?

**Comment by cloud9tn** [comment]
I tried 3 new urls.

**Comment by samuelselvan** [comment]
Can you provide the request ids?

**Comment by cloud9tn** [comment]
Certainly I wouldnt do it publicly on this forum as those ids are directly
linked to me.

**Comment by ashwinb** [comment]
Can you try using the `llama download` CLI as part of the `llama-toolchain` pip package? Let us know if that fares any better. Thank you!

**Comment by jstmn** [comment]
same error. `llama download` didn't work for me either
