### ISSUE TITLE
Incomplete installation instructions

### ISSUE THREAD

**Issue by eladkolet** [meta-llama/llama-models#34]
The installation instructions on this repo mention to run ./download.sh. but does not link to https://github.com/meta-llama/llama where the script is

**Comment by knibesh** [comment]
`./download.sh`can be found inside the respective `models` directory

**Comment by eladkolet** [comment]
Would be good to call it out in the instructions :)

**Comment by knibesh** [comment]
Indeed ! :)

**Comment by dcsw2** [comment]
zsh: 'Permission Denied' error in Bash...; same via fine-grained HF token.
