### ISSUE TITLE
Windows users cannot download Llama models!!

### ISSUE THREAD

**Issue by ayushman1024** [meta-llama/llama-models#35]
I got bash, wget, md5sum  but it gets connection error. Same issue was with earlier version now with 3.1 launch. Why you guys don't make windows specific download methods. I am sure lots of windows users are turning away because of this issue.

**Comment by jatin711-debug** [comment]
Hi @ayushman1024 , I had just created a PowerShell script to add to PR; once approved, you can use that to download models using windows, I hope that helps. 
Checkout the PR: https://github.com/meta-llama/llama-models/pull/41

**Comment by ashwinb** [comment]
Please use the `llama download` CLI method from the `llama-toolchain` pip package. Re-open this issue if that does not work.
