### ISSUE TITLE
Error while running bash ./download.sh command

### ISSUE THREAD

**Issue by jatin711-debug** [meta-llama/llama-models#38]
Running on WSL2 ubuntu 20.04
python - 3.8
Installed all required dependencies.
when doing bash ./download.sh, following error occurs ->

./download.sh: line 2: $'\r': command not found
./download.sh: line 9: $'\r': command not found
./download.sh: line 12: $'\r': command not found
: invalid optionine 13: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./download.sh: line 14: $'\r': command not found
': not a valid identifieread: `PRESIGNED_URL

 **** Model list ***
./download.sh: line 19: syntax error near unexpected token `$'do\r''
'/download.sh: line 19: `do

**Comment by samuelselvan** [comment]
@jatin711-debug this does not look anything specific to download.sh but more of your local bash env.
