### ISSUE TITLE
error msg when try to download llama 3.1

### ISSUE THREAD

**Issue by free-hero** [meta-llama/llama-models#39]
error msg when try to download

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6F0DPXTRCWJWMVM8</RequestId>
<HostId>xej17m2R/2Nm2mMGTzit8lhhurQOHhveLwSJesQEnq8r9GKmHQTE6NLMHNjKNainZ4tEXIqQu84=</HostId>
</Error>

**Comment by ThePythonDev** [comment]
How did you try to download it?
If possible you might want to try running as superuser (sudo)

**Comment by samuelselvan** [comment]
@free-hero I doubt if this is related to the download mechanism.

**Comment by melgabay** [comment]
Hey how did you fix the issue please?
