### ISSUE TITLE
how to download and use Meta-Llama-3.1-8B ?  Prompt 403 error

### ISSUE THREAD

**Issue by Juvarunst** [meta-llama/llama-models#43]
I am already there "https://llama.meta.com/llama-downloads" I applied for a unique custom URL, but the first download still prompted "403: Forbidden". Why? Has anyone encountered the same problem before?

![err](https://github.com/user-attachments/assets/ecb48b22-5ee6-48d3-909a-8be1d1aa1493)
![err2](https://github.com/user-attachments/assets/e4edf25b-168a-4680-a792-e9d567d9baac)

**Comment by samuelselvan** [comment]
@Juvarunst can you give a try again with a new url?

**Comment by Juvarunst** [comment]
> @Juvarunst can you give a try again with a new url?

this is a new url 
![555](https://github.com/user-attachments/assets/0f67169a-78b3-4ae0-ac76-aa1414226c17)

But problems still exist.
![666](https://github.com/user-attachments/assets/4b2ae12d-72df-4cf5-89cf-3ca88bda2b74)

This is an error message:


DESKTOP-021DSF0@DESKTOP-K155IV6 MINGW64 /e/llama-models/models/llama3_1 (main)
$ ./download.sh
Enter the URL from email: https://llama3-1.llamameta.net/*?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoicGE1b285cWtuaHh5cDJobzU1N3owanI1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMTk4MDEzN319fV19&Signature=PKCNtwULIKJS-YeZJSdYH5NsoSQAKw7Ra%7E3IAn%7E4CwQhxrfdn5mXdnPx6wRrtLEFKoIhdOyFCRf9-y98xJAKzh1kdCgBLiPEqms3Y3DNabH8CZaf7Hkk0q5tl3zARXhr17hpaks-%7E8CM7IZbhVV67B-E9k9iswneClJY6lACG4FkNO%7EzBrSGSJW-ENoLHyVtmDJS%7Eoan9Gk2UGGx9UV7xF0jmz3lKiD%7ERRwB7hDJd9K3T4EgKqhe0jzXur2hT7myqfFpXBtOUpS4rI5e6FVpNeJYB3vdeR2yC4bOdeLChsevQqKW5gsqu8FGKmPcaqHEniOrMhGM6RoKk-ZJxoeItQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=391358116864261

 **** Model list ***
 -  meta-llama-3.1-405b
 -  meta-llama-3.1-70b
 -  meta-llama-3.1-8b
 -  meta-llama-guard-3-8b
 -  prompt-guard
Choose the model to download: meta-llama-3.1-8b

 Selected model: meta-llama-3.1-8b

 **** Available models to download: ***
 -  meta-llama-3.1-8b-instruct
 -  meta-llama-3.1-8b
Enter the list of models to download without spaces or press Enter for all: meta-llama-3.1-8b
Downloading LICENSE and Acceptable Usage Policy
--2024-07-25 15:54:44--  https://llama3-1.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoicGE1b285cWtuaHh5cDJobzU1N3owanI1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMTk4MDEzN319fV19&Signature=PKCNtwULIKJS-YeZJSdYH5NsoSQAKw7Ra~3IAn~4CwQhxrfdn5mXdnPx6wRrtLEFKoIhdOyFCRf9-y98xJAKzh1kdCgBLiPEqms3Y3DNabH8CZaf7Hkk0q5tl3zARXhr17hpaks-~8CM7IZbhVV67B-E9k9iswneClJY6lACG4FkNO~zBrSGSJW-ENoLHyVtmDJS~oan9Gk2UGGx9UV7xF0jmz3lKiD~RRwB7hDJd9K3T4EgKqhe0jzXur2hT7myqfFpXBtOUpS4rI5e6FVpNeJYB3vdeR2yC4bOdeLChsevQqKW5gsqu8FGKmPcaqHEniOrMhGM6RoKk-ZJxoeItQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=391358116864261
Resolving llama3-1.llamameta.net (llama3-1.llamameta.net)... 3.165.21.92, 3.165.21.59, 3.165.21.74, ...
Connecting to llama3-1.llamameta.net (llama3-1.llamameta.net)|3.165.21.92|:443... failed: Bad file descriptor.
Connecting to llama3-1.llamameta.net (llama3-1.llamameta.net)|3.165.21.59|:443... failed: Bad file descriptor.
Connecting to llama3-1.llamameta.net (llama3-1.llamameta.net)|3.165.21.74|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-25 15:54:49 ERROR 403: Forbidden.

--2024-07-25 15:54:49--  https://llama3-1.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoicGE1b285cWtuaHh5cDJobzU1N3owanI1IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvbGxhbWEzLTEubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyMTk4MDEzN319fV19&Signature=PKCNtwULIKJS-YeZJSdYH5NsoSQAKw7Ra%7E3IAn%7E4CwQhxrfdn5mXdnPx6wRrtLEFKoIhdOyFCRf9-y98xJAKzh1kdCgBLiPEqms3Y3DNabH8CZaf7Hkk0q5tl3zARXhr17hpaks-%7E8CM7IZbhVV67B-E9k9iswneClJY6lACG4FkNO%7EzBrSGSJW-ENoLHyVtmDJS%7Eoan9Gk2UGGx9UV7xF0jmz3lKiD%7ERRwB7hDJd9K3T4EgKqhe0jzXur2hT7myqfFpXBtOUpS4rI5e6FVpNeJYB3vdeR2yC4bOdeLChsevQqKW5gsqu8FGKmPcaqHEniOrMhGM6RoKk-ZJxoeItQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=391358116864261
Reusing existing connection to llama3-1.llamameta.net:443.
HTTP request sent, awaiting response... 403 Forbidden
2024-07-25 15:54:49 ERROR 403: Forbidden.


DESKTOP-021DSF0@DESKTOP-K155IV6 MINGW64 /e/llama-models/models/llama3_1 (main)
$

**Comment by Juvarunst** [comment]
![Download Llama](https://github.com/user-attachments/assets/5a6d5d14-cd2b-4866-ac1b-1b633aca1457)


> @Juvarunst can you give a try again with a new url?

**Comment by innerpeacez** [comment]
same

**Comment by linfun486** [comment]
same

**Comment by astandrik** [comment]
same

**Comment by RCHTID** [comment]
exact same issue

**Comment by samuelselvan** [comment]
@Juvarunst - I checked url request (from the [Download-Request-ID=391358116864261). I see that URL has been used 5-6 times. You sure this is the first time its used?

Also for others I do need the Download-Request-ID url param to debug.

**Comment by suyin2** [comment]
same,has anyone solved the problem?

**Comment by jstmn** [comment]
same error

**Comment by kalyani7195** [comment]
same error

**Comment by ashwinb** [comment]
Please do not use `download.sh` -- you should use `llama` CLI obtained by installing the `llama-stack` pip package.
