### ISSUE TITLE
What's the differences between "<|eot_id|>" and "<|eom_id|>"?

### ISSUE THREAD

**Issue by kongjiellx** [meta-llama/llama-models#44]
Please!

**Comment by leoperegrino** [comment]
https://github.com/meta-llama/llama-models/blob/67468d1a648e7de474691410a147741bc8b3868c/models/llama3_1/api/tokenizer.py#L75-L76

**Comment by kongjiellx** [comment]
> https://github.com/meta-llama/llama-models/blob/67468d1a648e7de474691410a147741bc8b3868c/models/llama3_1/api/tokenizer.py#L75-L76

but when should I use eom?

**Comment by ashwinb** [comment]
See https://llama.meta.com/docs/model-cards-and-prompt-formats/llama3_1/ for an explanation. end-of-message is output by the model along with a tool-call -- the expectation is that the inference environment will treat it as a stop token, inspect the tool call, execute it and then feed the result back to the model for continued thinking.
