### ISSUE TITLE
Open-sourcing prompts used in data filtration

### ISSUE THREAD

**Issue by pluiez** [meta-llama/llama-models#45]
Hi, I'm wondering if you could release the prompts used for annotating data, including quality scoring and difficulty scoring for SFT data.

**Comment by varunfb** [comment]
Please read the [Llama 3.1](https://ai.meta.com/research/publications/the-llama-3-herd-of-models/) to learn more about how we have trained the llama models for more information about prompts, data processing techniques etc.
