### ISSUE TITLE
Error:Bad substitution 

### ISSUE THREAD

**Issue by xiaoToby** [meta-llama/llama-models#54]
I use the script （models/llama3_1/download.sh）
And I paste the url from meta website, 
![image](https://github.com/user-attachments/assets/29a6fa3f-d59c-4ae5-98fb-9ca75f1b7c15)

![image](https://github.com/user-attachments/assets/9c2cedf9-faca-441c-bf24-2bf59e8e9acf)

**Comment by xiaoToby** [comment]
Should use : bash download.sh

**Comment by ashwinb** [comment]
thanks! `download.sh` is now superceded anyhow by `llama download` (via the `llama-toolchain` pip package.)
