### ISSUE TITLE
How to reapply for model access on Huggingface?

### ISSUE THREAD

**Issue by ssslakter** [meta-llama/llama-models#60]
Hi!
I think there is no way to re-apply for access to the Llama models on the Hugging Face website. My requests were rejected without any explanation, even though I got access from the Meta site. It's very inconvenient, and I believe you should be able to re-apply at least.
There is also a Discord thread with a HF team member that has more details: https://discord.com/channels/879548962464493619/1248295028925792376

**Comment by ethahtz** [comment]
I got the same issue with llama3.2 :(

**Comment by ssslakter** [comment]
Basically what I ended up doing is I've created a new hf account and applied from it. Going to close this issue as I don't expect any response from meta team.
