### ISSUE TITLE
PyPI Not Updated Causing llama_toolchain CLI to Fail

### ISSUE THREAD

**Issue by pherrusa7** [meta-llama/llama-models#71]
## Issue Summary
The recent change in commit  [1dfcbc787681fe9768ecc729ca80737532e3567d](https://github.com/meta-llama/llama-models/commit/1dfcbc787681fe9768ecc729ca80737532e3567d#r144736223)  is causing the [llama model template](https://github.com/meta-llama/llama-toolchain/blob/dd6c1f1e6432e5f9dbc9b24d8a7fa0e64686814e/llama_toolchain/cli/model/template.py#L82) CLI command to fail on the main branch of [llama-toolchain](https://github.com/meta-llama/llama-toolchain/tree/main).

## Root Cause
The current [PyPI](https://pypi.org/project/llama-models/) version of llama-models (0.0.1) does not include the latest changes from the main branch of this repo. As a result, installing llama-toolchain does not fetch these necessary updates.

## Request
Could someone please push a new version of llama-models to PyPI to include the latest changes?

**Comment by ashwinb** [comment]
We just updated the packages now and landed major changes to all the repositories. Thank you for reporting though; really appreciate it.
