### ISSUE TITLE
MD5 Checksums for Llama 3.1

### ISSUE THREAD

**Issue by minimalic** [meta-llama/llama-models#73]
There is no checksum file for Llama 3.1 to verify the download.

**Comment by jeffreydunaway** [comment]
`ls -l ` I'm assuming you've done this for llama_3.1?

**Comment by minimalic** [comment]
Seriously?

**Comment by gtbkul** [comment]
Hi, I couldn't find any checksums. Would you be able to please point me in the right direction 

Thank!

**Comment by ashwinb** [comment]
If you use the new `llama download` CLI command part of the `llama-toolchain` package, you can get these checksums now. Thanks to @samuelselvan for adding them. Please re-open if this somehow is not sufficient or you encounter problems.

**Comment by gtbkul** [comment]
@ashwinb thanks for providing an update! Unfortunately I am not able to find an option to get the checksums. Please help me with the steps to access them.

Thank!

**Comment by Itime-ren** [comment]
same question @minimalic @ashwinb
