### ISSUE TITLE
Add the remaining Llama models

### ISSUE THREAD

**Issue by xNul** [meta-llama/llama-models#83]
The only Llama models added to this package are from the Llama 3.1 model family. It would be nice to have LLaMA (Llama 1), Llama 2, Llama 3, and Code Llama as well. Especially since now that `llama-toolchain` can only download models listed in this package.

**Comment by dltn** [comment]
Thanks for the suggestion! Addressed in https://github.com/meta-llama/llama-models/commit/3214718f53deec534b9529266e860e84dfb60d2f.
