### ISSUE TITLE
Users or devs, PLEASE provide checksums or digests

### ISSUE THREAD

**Issue by gtbkul** [meta-llama/llama-models#89]
Hello!

The 405B models are quite big. Please provide checksums or digests for each of the consolidated.**.pth

While we wait for Meta devs to provide them, users who are able to download them succesfully please provide the checksums in the comments so we can help each other verify!

Thank you!!

**Comment by gtbkul** [comment]
Here are mine, please let me know if there are any differences:
8e6042b4b7b3df2f0b11ca6dc577ddee042b16a35db7a9d1d53389c924a05ccb  consolidated.00.pth
78739e8ae399d6e4ac43c921d283a013fa6fc78a4341d26d304ecac87c973db1  consolidated.01.pth
cc4067ed1b1ef4970bd1db9aaa114f42314b5a5e40d1d799b6073bf0e811ea3a  consolidated.02.pth
8529538d1b5195a44471bb4c1ce0f316413022bb87718b4d3eed9b616cec0491  consolidated.03.pth
b1b28e23dab08bcd4212bc8ba7b619815f4f1ccb8bc05684b26802fe39283b98  consolidated.04.pth
4a9a16b3a21f427d517fb1a0aec8e6454dcd26f646da4fef53b27dfb8dd3fca3  consolidated.05.pth
4a78e216d7fcc9796ffdeeb449a75421cff5c8b6518d006a7a4f7c4b7c2a8fa0  consolidated.06.pth
28b6088f3f24d0540c36e8161f9c6b0262862bf6dc4deca425b98f69b956dc26  consolidated.07.pth
bf4587a5f278665bc739deef965e61c5b1474483c48b352c11bd278d4d22141a  consolidated.08.pth
eefc5e006c6c0cfe7ed8c58a39c58b63fea57076c7dcba6c9b862f9f2867bac2  consolidated.09.pth
96dc782ef27c7add143aa5f3f8815c2086f688c22e8f4ce4566aa5d23b1fb86b  consolidated.10.pth
ed180cf0421a92484bba83a9854121799f962749e989422ed97cc79c8d56812e  consolidated.11.pth
e673ca83eb6cd2373793a27d085fe830a619bec028e4a29d77469584aae1b775  consolidated.12.pth
fbb9ecaaa16c469b4673ed3865a47c51e72e5492c760906d0fb2b63201823b15  consolidated.13.pth
845a88e123074667cc2044b22aed6d3e7713eff0e9e2c4b70a69f7aa9c96ca1e  consolidated.14.pth
446f396bbf492ab5c33eb6084d80db147878e262ad978df0fa73e026fbb7f8aa  consolidated.15.pth

**Comment by ashwinb** [comment]
If you use `llama download` from the `llama-toolchain` PIP package, it should download the checksum files now. Thanks to @samuelselvan for adding these.

**Comment by gtbkul** [comment]
Hi,

I am still not able to find the checksums. Please guide me.

Thank you!!

**Comment by ashwinb** [comment]
Please tell me more about what you tried? Did you invoke `llama download --source meta --model-id <...>` That should download a `checklist.chk` file in the `~/.llama/checkpoints/<model_id>/` directory
